import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/SideBar/SideBar";
import { Infobar } from "@/components/InfoBar/InfoBar";

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col h-screen overflow-x-hidden">
      <header className="header">
        <Infobar />
      </header>
      <div className="flex flex-grow">
        <aside className="sidebar">
          <Sidebar />
        </aside>
        <main className="main-content flex-grow">
          {children}
        </main>
      </div>
    </div>
  );
}